#This is the name of the workflow that will be displayed in Actions Tab
name: CICD

#Manual click (Delivery) workflow whenever user needs
on:
  push:
      branches: [main]

      paths:
          - '**.html'

#These are the jobs inside the workflow_call
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              run: echo "Code clone from github"

    build:
        needs: [code]
        runs-on: ubuntu-latest
        steps:
            - name: Build Docker Container
              run: echo "Docker container build"

    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Test the conatiner
              run: echo "Testing the docker container"

    deploy:
        needs: [build,test]
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the application
              run: echo "Docker compose Deploying Application"
        
        
        
