name: Deploy Flask App

on: 
    workflow_run:          #Trigger the workflow when workflow "docker-build-push" is completed
        workflows: ["Docker build & Push"]       #Name of the workflow to listen for
        types: [completed]                       #Trigger only when the specified workflow is completed
        branches: [main]                         


jobs:
    deploy:
        runs-on: self-hosted         #Use self-hosted runner (VM) where the application will be deployed
        env:
            DOCKERHUB_USER: ${{vars.DOCKERHUB_USER}}      #Environment variable for Docker Hub username, can be used in the workflow steps
            DOCKER_TAG: ${{github.sha}}          #using the commit SHA to get unique tags for each build
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup docker compose (optional)       #Setup Docker Compose on the self-hosted runner if it's not already installed, using the official GitHub Action for Docker Compose
              uses: docker/setup-compose-action@v2

            - name: deploy with docker compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always   #Stop any running containers, then start new ones in detached mode, rebuilding images if necessary, forcing recreation of containers, and always pulling the latest images from the registry

